baseurl = "/"
languageCode = "en-gb"
title = "Wilberforce Travel Insurance"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Wilberforce Travel Insurance"
	description = "Wilberforce Travel Insurance, providing you with the best quotes in travel insurance."

	# The path must be relative to the static folder
	favicon = "img/favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Wilberforce Travel Insurance"

		[params.navigation.links]
			about     = "About"
			services  = "Quote"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Wilberforce Travel Insurance"
		subtitle   = ""
		buttonText = "About Us"


	# About section
	[params.about]
		headline    = "In business since 1924!"
		descriptionOne = "Wilberforce travel insurance have partnered with Just Insurance Agents Limited – one of the UKs leading providers of specialist Travel Insurance. Since 2004 Just Insurance Agents Limited has established itself as a market leader in the delivery of high quality and competitive travel insurance."
        descriptionTwo = "Just Insurance Agents Limited, work with a panel of insurers to offer a range of policies to suit all needs. You can compare and buy travel insurance products easily online, simply select Get a Quote, enter your travel details and select the cover that suits your needs most."
        descriptionThree = "So whether you are planning to lie on a beach, slide down a mountain, travel the seas or see the sights getting the right travel insurance couldn’t be easier.\nInsure your next adventure through us."
		buttonText  = "Find out more"


	# Service section
	[params.services]
		headline = "What we can offer"
        buttonText = "Get A Quote Now!"

        [[params.services.list]]
			icon = "maki make-fw maki-airport"
			title = "Travel Insurance"
			description = "Wilberforce travel insurance gives you access to a panel of insurers so that you can compare travel insurance prices and choose the policy that suits your needs best."

        [[params.services.list]]
            icon = "maki make-fw maki-skiing"
            title = "Winter Sports"
            description = "Cover is available for winter sports - ski and snowboard insurance, cruise insurance, travel insurance with pre-existing medical conditions and travel insurance for over 60, over 65 and over 70 years of age."

        [[params.services.list]]
            icon = "maki make-fw maki-rocket"
            title = "Single Trip"
            description = "Wilberforce travel insurance provides an instant solution for single trip travel insurance for a range of different holiday types and holiday makers."

        [[params.services.list]]
            icon = "maki make-fw maki-lodging"
            title = "Multi Trip"
            description = "Wilberforce travel insurance is able to offer both single trip travel insurance and annual multi trip  policies for individuals, couples, families and groups."

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contact us!"
		description = "Send us a message or get in touch for information on what else we can offer."
		phone = "+44 (0)1482 627383"
		email = "hello@wilberforceinsurance.co.uk"

        [params.contact.form]
            # Set custom strings for the form if your native
            # language isn't English
            name = "Name"
            email = "Email"
            message = "Message"
            submit = "Send message"
